### PR TITLE
Added image with link opening in a new tab

### PR DESCRIPTION
**Pull request by fabala**
This patch adds an html anchor around image tags in order to open them in a new tab when clicking on them.

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks! Can you just replace the `var` with a `const` to fix the CI?

**Comment by fabala** [comment]
Done!

**Comment by fabala** [comment]
Yohan, just one question: when this will be available thru npm?

**Comment by sinedied** [comment]
It's now available in `1.4.1`: I just had to add a small fix for the case where an image already had a link on it. 😉

**Pull request merged**
